# This is a workflow to create github release for a tag and publish the package to npm repo
name: Release

permissions:
  contents: read

on:
  push:
    tags:
      - "v*"
      # patterns to match for tag creation. Here all tags similar to v1.0 or
      # v1.2.0 will trigger this action
      - "v[0-9]+.[0-9]+.[0-9]+*"
      
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm ci
      - name: Build js
        run: npm run build
      - name: Publish to NPM with latest tag
        if: ${{ needs.setup_variables.outputs.isLatest == 'true' }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish to NPM with next tag
        if: ${{ needs.setup_variables.outputs.isLatest != 'true' }}
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
